USE [Curso]

-- SQL COMMAND TO CREATE A TABLE AND TURN ID AS ITS PRIMARY KEY
CREATE TABLE [Aluno] (
    [Id] INT NOT NULL UNIQUE,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT NOT NULL DEFAULT(0),

    PRIMARY KEY([Id])
    --PRIMARY KEY([Id], [Email]) -- SQL COMMAND TO TURN TWO OR MORE COLUMNS AS A COMPOSITE KEY
)
GO

-- SQL COMMAND TO ALTER A TABLE MAKING ID COLUMN INTO A PRIMARY KEY
ALTER TABLE [Aluno]
    ADD PRIMARY KEY([Id])

-- SQK COMMAND TO DROP A TABLE CONSTRAINT (THEY ARE AUTOMATICALLY CREATED FOR PRIMARY AND FOREIGN KEYS AND COLUMNS MARKED AS UNIQUE)
ALTER TABLE [Aluno]
    DROP CONSTRAINT [PK_Aluno_]

-- SQL COMMAND TO CREATE A TABLE WITH A CONSTRAINT FOR ITS PRIMARY KEY AND EMAIL

CREATE TABLE [Aluno] (
    [Id] INT NOT NULL UNIQUE,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Nascimento] DATETIME NULL,
    [Active] BIT NOT NULL DEFAULT(0),

    CONSTRAINT [PK_Aluno] PRIMARY KEY([Id]),
    CONSTRAINT [UQ_Aluno_Email] UNIQUE([Email])
)
GO