USE [Cursos]

-- SQL COMMAND TO CREATE A TABLE WITH SOME CONSTRAINTS
CREATE TABLE [Aluno] (
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Nascimento] DATETIME NULL,
    [Active] BIT NOT NULL DEFAULT(0),
)
GO

-- SQL COMMAND TO ALTER A TABLE COLUMN TO BE NOT NULL
ALTER TABLE [Aluno]
    ALTER COLUMN [Active] BIT NOT NULL

-- SQL COMMAND TO CREATE A TABLE A NOT DUPLICABLE ID AND EMAIL
CREATE TABLE [Aluno] (
    [Id] INT NOT NULL UNIQUE,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT NOT NULL DEFAULT(0),
)
GO

