-- SQL COMMAND TO RETRIEVE DATA FROM A TABLE
SELECT
    * 
FROM
    [Curso]

-- SQL COMMAND TO RETRIEVE ONLY 2 REGISTERS FROM A TABLE
SELECT TOP 2
    * 
FROM
    [Curso]

-- SQL COMMAND TO RETRIEVE ONLY 2 REGISTERS FROM A TABLE SPECIFYING THE COLUMNS (BETTER PERFORMANCE)
SELECT TOP 2
    [Id], [Nome] 
FROM
    [Curso]

-- SQL COMMAND TO RETRIEVE ONLY 100 REGISTERS AVOIDING REPEATED DATA
SELECT DISTINCT TOP 100
    [Nome] 
FROM
    [Categoria]